/**
 * Total API Reference
 *
 * Este contrato se usara para generar los clientes con todos los servicios necesarios.  `!Uso exclusivo interno!`               --- 
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: support@brand4impact.com
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.brand4impact.client.models

import com.brand4impact.client.models.ApiSort

import com.fasterxml.jackson.annotation.JsonProperty

/**
 * 
 *
 * @param pages 
 * @param propertySize 
 * @param elements 
 * @param sort 
 */

data class Pagination (

    @field:JsonProperty("pages")
    val pages: kotlin.Int? = null,

    @field:JsonProperty("size")
    val propertySize: kotlin.Int? = null,

    @field:JsonProperty("elements")
    val elements: kotlin.Long? = null,

    @field:JsonProperty("sort")
    val sort: ApiSort? = null

)

