/**
 * Total API Reference
 *
 * Este contrato se usara para generar los clientes con todos los servicios necesarios.  `!Uso exclusivo interno!`               --- 
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: support@brand4impact.com
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.brand4impact.client.models


import com.fasterxml.jackson.annotation.JsonProperty

/**
 * 
 *
 * @param street 
 * @param other 
 * @param postalcode 
 * @param city 
 * @param country 
 */

data class PlatformCompanyLegalAddress (

    @field:JsonProperty("street")
    val street: kotlin.String? = null,

    @field:JsonProperty("other")
    val other: kotlin.String? = null,

    @field:JsonProperty("postalcode")
    val postalcode: kotlin.String? = null,

    @field:JsonProperty("city")
    val city: kotlin.String? = null,

    @field:JsonProperty("country")
    val country: kotlin.String? = null

)

