/**
 * Total API Reference
 *
 * Este contrato se usara para generar los clientes con todos los servicios necesarios.  `!Uso exclusivo interno!`               --- 
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: support@brand4impact.com
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.brand4impact.client.models

import com.brand4impact.client.models.PlatformInvoiceEntryBase

import com.fasterxml.jackson.annotation.JsonProperty

/**
 * 
 *
 * @param concept 
 * @param units 
 * @param base 
 * @param taxes 
 */

data class PlatformInvoiceEntry (

    @field:JsonProperty("concept")
    val concept: kotlin.String? = null,

    @field:JsonProperty("units")
    val units: kotlin.Int? = null,

    @field:JsonProperty("base")
    val base: PlatformInvoiceEntryBase? = null,

    @field:JsonProperty("taxes")
    val taxes: PlatformInvoiceEntryBase? = null

)

