/**
 * Total API Reference
 *
 * Este contrato se usara para generar los clientes con todos los servicios necesarios.  `!Uso exclusivo interno!`               --- 
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: support@brand4impact.com
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.brand4impact.client.models

import com.brand4impact.client.models.PlatformCompanyLegalAddress

import com.fasterxml.jackson.annotation.JsonProperty

/**
 * 
 *
 * @param token 
 * @param firstname 
 * @param lastname 
 * @param nid 
 * @param brithday 
 * @param nationality 
 * @param residence 
 * @param email 
 * @param address 
 */

data class PlatformCompanyLegal (

    @field:JsonProperty("token")
    val token: kotlin.String? = null,

    @field:JsonProperty("firstname")
    val firstname: kotlin.String? = null,

    @field:JsonProperty("lastname")
    val lastname: kotlin.String? = null,

    @field:JsonProperty("nid")
    val nid: kotlin.String? = null,

    @field:JsonProperty("brithday")
    val brithday: java.time.OffsetDateTime? = null,

    @field:JsonProperty("nationality")
    val nationality: kotlin.String? = null,

    @field:JsonProperty("residence")
    val residence: kotlin.String? = null,

    @field:JsonProperty("email")
    val email: kotlin.String? = null,

    @field:JsonProperty("address")
    val address: PlatformCompanyLegalAddress? = null

)

