/**
 * Total API Reference
 *
 * Este contrato se usara para generar los clientes con todos los servicios necesarios.  `!Uso exclusivo interno!`               --- 
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: support@brand4impact.com
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.brand4impact.client.models

import com.brand4impact.client.models.PlatformCompanyAddress
import com.brand4impact.client.models.PlatformCompanyLegal

import com.fasterxml.jackson.annotation.JsonProperty

/**
 * 
 *
 * @param token 
 * @param id 
 * @param name 
 * @param vat 
 * @param status 
 * @param address 
 * @param legal 
 * @param sectorToken 
 * @param topicsToken 
 */

data class PlatformCompany (

    @field:JsonProperty("token")
    val token: kotlin.String? = null,

    @field:JsonProperty("id")
    val id: kotlin.String? = null,

    @field:JsonProperty("name")
    val name: kotlin.String? = null,

    @field:JsonProperty("vat")
    val vat: kotlin.String? = null,

    @field:JsonProperty("status")
    val status: kotlin.String? = null,

    @field:JsonProperty("address")
    val address: PlatformCompanyAddress? = null,

    @field:JsonProperty("legal")
    val legal: PlatformCompanyLegal? = null,

    @field:JsonProperty("sectorToken")
    val sectorToken: kotlin.String? = null,

    @field:JsonProperty("topicsToken")
    val topicsToken: kotlin.collections.List<kotlin.String>? = null

)

